name: Force Build Docker image

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version(s) to build"
        required: true
        default: "all"
        type: choice
        options:
          - release
          - dev
          - all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set version
        id: set-version
        run: |
          echo "version=$(cat Tag | head -n1)" >> $GITHUB_OUTPUT
          echo "version_dev=$(cat TagDev | head -n1)" >> $GITHUB_OUTPUT

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push to Docker Hub (release)
        if: inputs.version == 'release' || inputs.version == 'all'
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile
          platforms: linux/arm/v7,linux/arm64,linux/amd64
          push: true
          tags: |
            ani1ak/singbox-vless-mikrotik:${{ steps.set-version.outputs.version }}
            ani1ak/singbox-vless-mikrotik:latest
            ghcr.io/${{ github.repository }}:${{ steps.set-version.outputs.version }}
            ghcr.io/${{ github.repository }}:latest
          build-args: |
            SINGBOX_VERSION=${{ steps.set-version.outputs.version }}

      - name: Build and Push to Docker Hub (dev)
        if: inputs.version == 'dev' || inputs.version == 'all'
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile
          platforms: linux/arm/v7,linux/arm64,linux/amd64
          push: true
          tags: |
            ani1ak/singbox-vless-mikrotik:${{ steps.set-version.outputs.version_dev }}
            ani1ak/singbox-vless-mikrotik:dev
            ghcr.io/${{ github.repository }}:${{ steps.set-version.outputs.version_dev }}
            ghcr.io/${{ github.repository }}:dev
          build-args: |
            SINGBOX_VERSION=${{ steps.set-version.outputs.version_dev }}

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ani1ak/singbox-vless-mikrotik
