name: Build Docker image

on:
  workflow_dispatch:
  schedule:
    - cron: "5 4,12,20 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update tags and commit changes
        id: up-version
        run: bash .github/workflows/update_tag.sh

      - name: Set version
        if: steps.up-version.outputs.status == 'success' || steps.up-version.outputs.status_dev == 'success'
        id: set-version
        run: |
          echo "version=$(cat Tag | head -n1)" >> $GITHUB_OUTPUT
          echo "version_dev=$(cat TagDev | head -n1)" >> $GITHUB_OUTPUT

      - name: Setup Docker meta (release)
        if: steps.up-version.outputs.status == 'success'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ani1ak/singbox-vless-mikrotik
            ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}},value=${{ steps.set-version.outputs.version }}
            type=raw,value=latest

      - name: Setup Docker meta (dev)
        if: steps.up-version.outputs.status_dev == 'success'
        id: meta_dev
        uses: docker/metadata-action@v5
        with:
          images: |
            ani1ak/singbox-vless-mikrotik
            ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}},value=${{ steps.set-version.outputs.version_dev }}
            type=raw,value=dev

      - name: Setup QEMU
        if: steps.up-version.outputs.status == 'success' || steps.up-version.outputs.status_dev == 'success'
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        if: steps.up-version.outputs.status == 'success' || steps.up-version.outputs.status_dev == 'success'
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: steps.up-version.outputs.status == 'success' || steps.up-version.outputs.status_dev == 'success'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        if: steps.up-version.outputs.status == 'success' || steps.up-version.outputs.status_dev == 'success'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push (release)
        if: steps.up-version.outputs.status == 'success'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm/v7,linux/arm64,linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            SINGBOX_VERSION=${{ steps.set-version.outputs.version }}

      - name: Build and Push (dev)
        if: steps.up-version.outputs.status_dev == 'success'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm/v7,linux/arm64,linux/amd64
          push: true
          tags: ${{ steps.meta_dev.outputs.tags }}
          labels: ${{ steps.meta_dev.outputs.labels }}
          build-args: |
            SINGBOX_VERSION=${{ steps.set-version.outputs.version_dev }}

      - name: Docker Hub Description
        if: steps.up-version.outputs.status == 'success' || steps.up-version.outputs.status_dev == 'success'
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ani1ak/singbox-vless-mikrotik
