name: Build on Dockerfile changes

on:
  workflow_dispatch:
  push:
    paths:
      - "Dockerfile"
      - "Tag"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Version
        id: set-version
        run: echo "version=$(cat Tag | head -n1)" >> $GITHUB_OUTPUT

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile
          platforms: linux/arm/v7,linux/arm64
          push: true
          tags: |
            ani1ak/singbox-mikrotik:${{ steps.set-version.outputs.version }}
            ani1ak/singbox-mikrotik:latest
          build-args: |
            SINGBOX_VERSION=${{ steps.set-version.outputs.version }}
