name: Update version tag

on:
  workflow_dispatch:
  schedule:
    - cron: "5 4 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update tags and commit changes
        run: bash .github/workflows/update_tag.sh
